import { SubscriptionPlan, UserSubscription } from '../types';

export const SUBSCRIPTION_PLANS: SubscriptionPlan[] = [
  {
    id: 'individual',
    name: 'Plan Individual',
    tagline: 'Control total de finanzas personales, gastos y cuotas. ¡15 días de prueba gratis!',
    badge: '15 Días Gratis 🎁',
    priceMonthly: 4900,
    priceAnnual: 39000, // Equivale a $3.250/mes (-34%)
    currency: 'ARS',
    maxUsers: 1,
    hasAiAssistant: false,
    hasCoupleSync: false,
    hasInstallmentManager: true,
    features: [
      '✨ 15 días de prueba GRATIS sin cargo inicial',
      '1 Usuario individual',
      'Carga y registro ilimitado de gastos e ingresos',
      'Metas de ahorro personalizadas y alcancías virtuales',
      'Control de compras en cuotas y vencimiento de tarjetas',
      'Presupuestos mensuales y límites de gastos',
      'Catálogo de categorías estándar predefinidas',
      'Exportación completa de reportes a CSV/Excel',
      'Soporte técnico por correo electrónico'
    ]
  },
  {
    id: 'pareja',
    name: 'Plan Parejas Dúo',
    tagline: 'Sincronización en tiempo real para 2 personas y finanzas de pareja. ¡15 días de prueba gratis!',
    badge: 'Más Elegido ⭐ (15 Días Gratis)',
    priceMonthly: 7900,
    priceAnnual: 63000, // Equivale a $5.250/mes (-34%)
    currency: 'ARS',
    isPopular: true,
    maxUsers: 2,
    hasAiAssistant: false,
    hasCoupleSync: true,
    hasInstallmentManager: true,
    features: [
      '✨ 15 días de prueba GRATIS para ambas cuentas',
      '2 Cuentas vinculadas sincronizadas en tiempo real',
      'Todo lo incluido en el Plan Individual',
      'Creación y edición ilimitada de categorías y subrubros propios',
      'Metas de ahorro compartidas y alcancías de pareja',
      'División inteligente: 50/50, 60/40, % personalizado o montos exactos',
      'Cálculo de balances y liquidaciones: quién le debe a quién',
      'Historial de acuerdos y pagos de saldos en pareja',
      'Filtro instantáneo entre gastos propios y de la pareja'
    ]
  },
  {
    id: 'pro_ai',
    name: 'Plan Pro & Asistente IA',
    tagline: 'Máxima potencia con registro inteligente de gastos por voz con IA y categorización automática. ¡15 días gratis!',
    badge: 'Potencia Total 🚀 (15 Días Gratis)',
    priceMonthly: 12500,
    priceAnnual: 99000, // Equivale a $8.250/mes (-34%)
    currency: 'ARS',
    isPro: true,
    maxUsers: 2,
    hasAiAssistant: true,
    hasCoupleSync: true,
    hasInstallmentManager: true,
    features: [
      '✨ 15 días de prueba GRATIS con registro por voz ilimitado',
      'Todo lo incluido en el Plan Parejas Dúo',
      'Creación y personalización total de categorías y subrubros',
      'Registro ultra-rápido de gastos por voz o audios de WhatsApp con IA',
      'Categorización inteligente automática (ej: "Gasté 50000 en Coto" → Alimentación Supermercado)',
      'Gestión de Vencimientos (Tarjetas, Alquiler, Expensas, Servicios e Impuestos) + Google Calendar 📅',
      'Soporte prioritario directo por WhatsApp 24/7',
      'Acceso anticipado a nuevas funciones exclusivas'
    ]
  }
];

export const INITIAL_USER_SUBSCRIPTIONS: UserSubscription[] = [
  {
    id: 'sub-101',
    userId: 'usr-001',
    userEmail: 'ejemplo@ejemplo.com',
    userName: 'Sol',
    partnerName: 'Martín',
    accountCode: 'PAREJA-2026',
    planId: 'pro_ai',
    planName: 'Plan Pro & Asistente IA',
    status: 'active',
    billingCycle: 'monthly',
    pricePaid: 12500,
    currency: 'ARS',
    paymentMethod: 'Mercado Pago',
    mercadopagoPaymentId: 'MP-984321045',
    startDate: '2026-08-01',
    lastPaymentDate: '2026-08-01',
    nextRenewalDate: '2026-09-01',
    createdAt: Date.now() - 28 * 86400000,
    autoRenew: true,
    notes: 'Cliente preferencial. Pago automático con Mercado Pago débito.'
  },
  {
    id: 'sub-102',
    userId: 'usr-002',
    userEmail: 'ejemplo2@ejemplo.com',
    userName: 'Lucas González',
    partnerName: 'Camila',
    accountCode: 'PAIR-8492',
    planId: 'pareja',
    planName: 'Plan Parejas Dúo',
    status: 'active',
    billingCycle: 'annual',
    pricePaid: 63000,
    currency: 'ARS',
    paymentMethod: 'Mercado Pago',
    mercadopagoPaymentId: 'MP-983190822',
    startDate: '2026-06-15',
    lastPaymentDate: '2026-06-15',
    nextRenewalDate: '2027-06-15',
    createdAt: Date.now() - 75 * 86400000,
    autoRenew: true,
    notes: 'Suscripción anual abonada con dinero en cuenta MP.'
  },
  {
    id: 'sub-103',
    userId: 'usr-003',
    userEmail: 'ejemplo3@ejemplo.com',
    userName: 'Mariano Silva',
    accountCode: 'IND-3391',
    planId: 'individual',
    planName: 'Plan Individual',
    status: 'active',
    billingCycle: 'monthly',
    pricePaid: 4900,
    currency: 'ARS',
    paymentMethod: 'Mercado Pago',
    mercadopagoPaymentId: 'MP-981204910',
    startDate: '2026-08-10',
    lastPaymentDate: '2026-08-10',
    nextRenewalDate: '2026-09-10',
    createdAt: Date.now() - 19 * 86400000,
    autoRenew: true
  },
  {
    id: 'sub-104',
    userId: 'usr-004',
    userEmail: 'ejemplo4@ejemplo.com',
    userName: 'Valeria Fernández',
    partnerName: 'Esteban',
    accountCode: 'PAIR-5512',
    planId: 'pareja',
    planName: 'Plan Parejas Dúo',
    status: 'pending_payment',
    billingCycle: 'monthly',
    pricePaid: 7900,
    currency: 'ARS',
    paymentMethod: 'Mercado Pago',
    mercadopagoPaymentId: 'MP-980041233',
    startDate: '2026-08-25',
    lastPaymentDate: '2026-07-25',
    nextRenewalDate: '2026-08-25',
    createdAt: Date.now() - 35 * 86400000,
    autoRenew: false,
    notes: 'Tarjeta rechazada por fondos insuficientes. Reintento programado.'
  },
  {
    id: 'sub-105',
    userId: 'usr-005',
    userEmail: 'ejemplo5@ejemplo.com',
    userName: 'Franco Rodríguez',
    accountCode: 'IND-9021',
    planId: 'individual',
    planName: 'Plan Individual',
    status: 'trial',
    billingCycle: 'monthly',
    pricePaid: 0,
    currency: 'ARS',
    paymentMethod: 'Mercado Pago (Prueba 15 Días)',
    startDate: '2026-08-22',
    lastPaymentDate: '2026-08-22',
    nextRenewalDate: '2026-09-06',
    trialEndsDate: '2026-09-06',
    trialDaysGranted: 15,
    createdAt: Date.now() - 7 * 86400000,
    autoRenew: true,
    notes: 'Período de prueba de 15 días activo (restan 6 días).'
  },
  {
    id: 'sub-106',
    userId: 'usr-006',
    userEmail: 'ejemplo6@ejemplo.com',
    userName: 'Sofía Martínez',
    partnerName: 'Tomás',
    accountCode: 'PAIR-3109',
    planId: 'pareja',
    planName: 'Plan Parejas Dúo',
    status: 'trial',
    billingCycle: 'monthly',
    pricePaid: 0,
    currency: 'ARS',
    paymentMethod: 'Mercado Pago (Prueba 15 Días)',
    startDate: '2026-08-10',
    lastPaymentDate: '2026-08-10',
    nextRenewalDate: '2026-08-25',
    trialEndsDate: '2026-08-25',
    trialDaysGranted: 15,
    createdAt: Date.now() - 21 * 86400000,
    autoRenew: false,
    notes: 'Prueba de 15 días vencida el 25/08/2026. Cuenta bloqueada pendiente de pago.'
  }
];
